var dataSet = [
  [
    1,
    '<img src="../img/handsome-adult-male-posing3.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'System Architect',
    'Edinburgh',
    '5421',
    '2011/04/25',
    '$320,800',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    2,
    '<img src="../img/handsome-adult-male-posing.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Accountant',
    'Tokyo',
    '8422',
    '2011/07/25',
    '$170,750',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    3,
    '<img src="../img/handsome-adult-male-posing2.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Junior Technical Author',
    'San Francisco',
    '1562',
    '2009/01/12',
    '$86,000',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    4,
    '<img src="../img/handsome-adult-male-posing4.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Senior Javascript Developer',
    'Edinburgh',
    '6224',
    '2012/03/29',
    '$433,060',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    5,
    '<img src="../img/handsome-adult-male-posing5.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Accountant',
    'Tokyo',
    '5407',
    '2008/11/28',
    '$162,700',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    6,
    '<img src="../img/handsome-adult-male-posing6.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Integration Specialist',
    'New York',
    '4804',
    '2012/12/02',
    '$372,000',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    7,
    '<img src="../img/handsome-adult-male-posing7.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Sales Assistant',
    'San Francisco',
    '9608',
    '2012/08/06',
    '$137,500',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    8,
    '<img src="../img/handsome-adult-male-posing8.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Integration Specialist',
    'Tokyo',
    '6200',
    '2010/10/14',
    '$327,900',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    9,
    '<img src="../img/handsome-adult-male-posing9.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Javascript Developer',
    'San Francisco',
    '2360',
    '2009/09/15',
    '$205,500',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    10,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Software Engineer',
    'Edinburgh',
    '1667',
    '2008/12/13',
    '$103,600',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    11,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Office Manager',
    'London',
    '3814',
    '2008/12/19',
    '$90,560',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    12,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Support Lead',
    'Edinburgh',
    '9497',
    '2013/03/03',
    '$342,000',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    13,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Regional Director',
    'San Francisco',
    '6741',
    '2008/10/16',
    '$470,600',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    14,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Senior Marketing Designer',
    'London',
    '3597',
    '2012/12/18',
    '$313,500',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    15,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Regional Director',
    'London',
    '1965',
    '2010/03/17',
    '$385,750',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    16,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Marketing Designer',
    'London',
    '1581',
    '2012/11/27',
    '$198,500',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    17,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Chief Financial Officer (CFO)',
    'New York',
    '3059',
    '2010/06/09',
    '$725,000',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    18,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Systems Administrator',
    'New York',
    '1721',
    '2009/04/10',
    '$237,500',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    19,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Software Engineer',
    'London',
    '2558',
    '2012/10/13',
    '$132,000',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    20,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Personnel Lead',
    'Edinburgh',
    '2290',
    '2012/09/26',
    '$217,500',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    21,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Development Lead',
    'New York',
    '1937',
    '2011/09/03',
    '$345,000',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    22,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Chief Marketing Officer (CMO)',
    'New York',
    '6154',
    '2009/06/25',
    '$675,000',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    23,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Pre-Sales Support',
    'New York',
    '8330',
    '2011/12/12',
    '$106,450',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    24,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Sales Assistant',
    'Sydney',
    '3023',
    '2010/09/20',
    '$85,600',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    25,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Chief Executive Officer (CEO)',
    'London',
    '5797',
    '2009/10/09',
    '$1,200,000',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    26,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Developer',
    'Edinburgh',
    '8822',
    '2010/12/22',
    '$92,575',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    27,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Regional Director',
    'Singapore',
    '9239',
    '2010/11/14',
    '$357,650',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    28,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Software Engineer',
    'San Francisco',
    '1314',
    '2011/06/07',
    '$206,850',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    29,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Chief Operating Officer (COO)',
    'San Francisco',
    '2947',
    '2010/03/11',
    '$850,000',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    30,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Regional Marketing',
    'Tokyo',
    '8899',
    '2011/08/14',
    '$163,000',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    31,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Integration Specialist',
    'Sydney',
    '2769',
    '2011/06/02',
    '$95,400',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    32,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Developer',
    'London',
    '6832',
    '2009/10/22',
    '$114,500',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    33,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Technical Author',
    'London',
    '3606',
    '2011/05/07',
    '$145,000',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    34,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Team Leader',
    'San Francisco',
    '2860',
    '2008/10/26',
    '$235,500',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    35,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Post-Sales support',
    'Edinburgh',
    '8240',
    '2011/03/09',
    '$324,050',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
  [
    36,
    '<img src="../img/handsome-adult-male-posing10.jpg" width="39px" alt="Avater" style="width: 2.8rem; height: 2.8rem; border-radius: 50%; overflow: hidden; object-fit: cover;"/>',
    'Marketing Designer',
    'San Francisco',
    '5384',
    '2009/12/09',
    '$85,675',
    '<div class="action"><button type="botton" data-bs-toggle="modal" data-bs-target="#viewUserModal"><i class="fa-regular fa-eye"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#editUserModal"><i class="fa-regular fa-pen-to-square"></i></button><button type="botton" data-bs-toggle="modal" data-bs-target="#deleteUserModal"><i class="fa-regular fa-trash-can"></i></button></div>',
  ],
];

$(document).ready(function () {
  $('#example').DataTable({
    scrollX: true,
    data: dataSet,
    columns: [
      { title: 'S/N' },
      { title: 'Photo' },
      { title: 'Name' },
      { title: 'E-mail' },
      { title: 'Number' },
      { title: 'Platoon' },
      { title: 'Gender' },
      { title: 'Action' },
    ],
  });
});
